//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKS_Thuc_Tap_Web.Sample_Page {
    
    
    public partial class Tim_Kiem {
        
        /// <summary>
        /// uc1315_Tim_Kiem1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TKS_Thuc_Tap_Web.Sample_Page.UserControl.uc1315_Tim_Kiem uc1315_Tim_Kiem1;
    }
}
