//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKS_Thuc_Tap_Web.Dashboard {
    
    
    public partial class Dashboard {
        
        /// <summary>
        /// uc8000_Dashboard1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TKS_Thuc_Tap_Web.Dashboard.UserControl.uc8000_Dashboard uc8000_Dashboard1;
    }
}
