//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKS_Thuc_Tap_Web.Dashboard.UserControl
{


    public partial class uc8000_Dashboard
    {
    }
}
